/**
 * Creates a Starknet deployer account and writes it to `.env.sepolia` (gitignored).
 *
 * The address is deterministic from the public key and the OpenZeppelin account class, so it
 * can be funded *before* it exists on-chain — which is the only way round the chicken-and-egg
 * of needing STRK to deploy the account that holds the STRK. `deploy-account.ts` then
 * publishes it once the balance lands.
 */

import { existsSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { CallData, ec, hash } from "starknet";

/** OpenZeppelin Account v1, confirmed declared on Sepolia and mainnet. */
const OZ_ACCOUNT_CLASS =
  "0x061dac032f228abef9c6626f995015233097ae253a7f72d68552db02f2971b8f";

const HERE = dirname(fileURLToPath(import.meta.url));
const ENV_PATH = join(HERE, "..", `.env.${process.env.NETWORK ?? "sepolia"}`);

function main(): void {
  if (existsSync(ENV_PATH) && !process.env.FORCE) {
    console.error(
      `${ENV_PATH} already exists. Refusing to overwrite an account that may hold funds.\n` +
        `Set FORCE=1 if you are certain you want a new one.`,
    );
    process.exit(1);
  }

  const privateKey = `0x${Buffer.from(ec.starkCurve.utils.randomPrivateKey()).toString("hex")}`;
  const publicKey = ec.starkCurve.getStarkKey(privateKey);
  const constructorCalldata = CallData.compile({ publicKey });
  const address = hash.calculateContractAddressFromHash(
    publicKey,
    OZ_ACCOUNT_CLASS,
    constructorCalldata,
    0,
  );

  const network = process.env.NETWORK ?? "sepolia";
  writeFileSync(
    ENV_PATH,
    [
      `# CrewKill deployer for ${network}. Generated by scripts/new-account.ts.`,
      `# This file is gitignored and holds a real private key — do not commit or paste it.`,
      `NETWORK=${network}`,
      `KEEPER_ADDRESS=${address}`,
      `KEEPER_PRIVATE_KEY=${privateKey}`,
      `KEEPER_PUBLIC_KEY=${publicKey}`,
      `ACCOUNT_CLASS_HASH=${OZ_ACCOUNT_CLASS}`,
      "",
    ].join("\n"),
    { mode: 0o600 },
  );

  console.log(`\n  network        ${network}`);
  console.log(`  account class  ${OZ_ACCOUNT_CLASS}`);
  console.log(`\n  FUND THIS ADDRESS WITH STRK:\n\n    ${address}\n`);
  console.log(`  Key written to ${ENV_PATH} (mode 600, gitignored).`);
  console.log(`  Then run: pnpm --filter @crewkill/keeper exec tsx scripts/deploy-account.ts\n`);
}

main();
